#ifndef HYDROFGEN_CONFIG_H
#define HYDROFGEN_CONFIG_H

#include <FastLED.h>

// LED Strip Configuration
#define NUM_LEDS 1000
#define DEFAULT_LED_COUNT NUM_LEDS
#define DATA_PIN 4
#define COLOR_ORDER GRB

// LED Segments
//Renewable energy production segments
#define WIND_LED_START 0
#define WIND_LED_END 5
#define SOLAR_LED_START 6
#define SOLAR_LED_END 11
#define ELECTRICITY_PRODUCTION_LED_START 12
#define ELECTRICITY_PRODUCTION_LED_END 16

// hydrogen production segment at the end of the strip
#define HYDROGEN_PRODUCTION_LED_START 150
#define HYDROGEN_PRODUCTION_LED_END 155
//hudrogen transport segment with MID used to trigger consumption
#define HYDROGEN_TRANSPORT_LED_START 136
#define HYDROGEN_TRANSPORT_LED_MID 142
#define HYDROGEN_TRANSPORT_LED_END 149

//hydrogen storage segments
#define HYDROGEN_STORAGE1_LED_START 34
#define HYDROGEN_STORAGE1_LED_END 35
#define HYDROGEN_STORAGE2_LED_START 40
#define HYDROGEN_STORAGE2_LED_END 45
// hydrogen consumption segment
#define HYDROGEN_CONSUMPTION_LED_START 46
#define HYDROGEN_CONSUMPTION_LED_END 51

// Fabrication segment with fire effect
#define FABRICATION_LED_START 100
#define FABRICATION_LED_END 109

//from electricity production to electricity consumption (made out off hydrogen)
#define ELECTRICITY_TRANSPORT_LED_START 52
#define ELECTRICITY_TRANSPORT_LED_END 60

#define STORAGE_TRANSPORT_LED_START 61
#define STORAGE_TRANSPORT_LED_END 65
#define STORAGE_POWERSTATION_LED_START 66
#define STORAGE_POWERSTATION_LED_END 71

// Info LEDs (now on separate digital pins instead of LED strip)
#define WIND_INFO_LED_PIN 15
#define ELECTROLYSER_INFO_LED_PIN 16
#define HYDROGEN_PRODUCTION_INFO_LED_PIN 17
#define HYDROGEN_STORAGE_INFO_LED_PIN 18
#define HYDROGEN_CONSUMPTION_INFO_LED_PIN 19
#define ELECTRICITY_TRANSPORT_INFO_LED_PIN 21
#define STREET_INFO_LED_PIN 22

// Colors
#define WIND_COLOR_ACTIVE CRGB(255, 255, 0)
#define HYDROGEN_PRODUCTION_COLOR_ACTIVE CRGB(0, 255, 0)
#define HYDROGEN_STORAGE_COLOR_ACTIVE CRGB(0, 255, 0)
#define HYDROGEN_CONSUMPTION_COLOR_ACTIVE CRGB(0, 255, 0)
#define ELECTRICITY_TRANSPORT_COLOR_ACTIVE CRGB(255, 255, 0)

// Timing
#define LED_DELAY 500
#define LED_DELAY2 100
#define BUTTON_CHECK_INTERVAL 250

// Button + pins
#define BUTTON_PIN 0
#define BUTTON_LED_PIN 2
#define STREET_LED_PIN 14

// Relays
#define WIND_TURBINE_RELAY_PIN 12
#define ELECTROLYSER_RELAY_PIN 13

// General timers
#define WIND_TIME_MS 20000U
#define RUN_TIME_MS 90000U
#define HYDROGEN_PRODUCTION_DELAY_MS 3000U
#define HYDROGEN_STORAGE_DELAY_MS 3000U

// Test-board diagnostics. Set to 0/240 for production ESP.
#define DIAG_DISABLE_BROWNOUT 0
#define DIAG_CPU_FREQ_MHZ 240

#endif